/**
 * VineBond — Rheingau Vineyard Dataset
 * ─────────────────────────────────────────────────────────────────────────────
 * Shared data layer consumed by all map renderers (Leaflet, Google Maps, Apple Maps).
 * 14 classified vineyard sites: 10 Grosses Gewächs (GG) + 4 Erstes Gewächs (1G).
 * ────��────────────────────────────────────────────────────────────────────────
 */

window.RHEINGAU_VINEYARDS = [
  /* ── Grosses Gewächs (GG) ──────────��─────────────────────────────���─────── */
  {
    id: 'johannisberg',
    name: 'Schloss Johannisberg',
    village: 'Johannisberg',
    type: 'GG',
    lat: 49.9858, lng: 7.9985,
    estate: 'Fürst von Metternich / Oetker Collection',
    grape: 'Riesling',
    soil: 'Lösslehm über Taunus-Quarzit',
    altitude: '145 m',
    slope: 'Süd',
    tours: ['Tasting', 'Cellar Tour'],
    desc_en: 'The world\'s oldest Riesling estate, continuously cultivated for over 1,200 years. The GG displays a characteristic mineral tension from deep loess over quartzite soils.',
    desc_de: 'Das älteste Riesling-Weingut der Welt — seit über 1.200 Jahren ununterbrochen bewirtschaftet. Das GG zeigt ausgeprägte mineralische Spannung aus tiefem Löss über Quarzit.'
  },
  {
    id: 'berg-schlossberg',
    name: 'Rüdesheimer Berg Schlossberg',
    village: 'Rüdesheim',
    type: 'GG',
    lat: 49.9792, lng: 7.9118,
    estate: 'Weingut Georg Breuer',
    grape: 'Riesling',
    soil: 'Quarzit, Phyllit-Schiefer',
    altitude: '80–240 m',
    slope: 'Süd, Südwest',
    tours: ['Tasting', 'Vineyard Walk'],
    desc_en: 'Steep south-facing slope with deep slate soils. The GG from Breuer is renowned for its extraordinary mineral precision and long-term ageing potential.',
    desc_de: 'Steile Süd- und Südwestlage mit tiefen Phyllitböden. Das GG von Breuer steht für außergewöhnliche mineralische Präzision und langes Alterungspotenzial.'
  },
  {
    id: 'marcobrunn',
    name: 'Erbacher Marcobrunn',
    village: 'Erbach',
    type: 'GG',
    lat: 49.9975, lng: 8.0510,
    estate: 'Schloss Schönborn / Knyphausen',
    grape: 'Riesling',
    soil: 'Schwerer Lehm über Kalkstein',
    altitude: '88 m',
    slope: 'Ost, Südost',
    tours: ['Tasting', 'Cellar Tour', 'Vineyard Walk'],
    desc_en: 'Historically the most significant Einzellage of the Rheingau, referenced in records since the 12th century. Rich, powerful style with excellent structure.',
    desc_de: 'Historisch bedeutendste Einzellage des Rheingaus, urkundlich seit dem 12. Jahrhundert belegt. Reicher, kraftvoller Ausbau mit exzellenter Struktur.'
  },
  {
    id: 'baiken',
    name: 'Rauenthaler Baiken',
    village: 'Rauenthal',
    type: 'GG',
    lat: 50.0282, lng: 8.0942,
    estate: 'Weingut Robert Weil',
    grape: 'Riesling',
    soil: 'Phyllitschiefer, Taunusquarzit',
    altitude: '200–280 m',
    slope: 'Süd',
    tours: ['Tasting', 'Vineyard Walk'],
    desc_en: 'The highest-elevated GG site in the Rheingau. A cool microclimate creates pronounced acidity and subtle spice, signature of the Rauenthal terroir.',
    desc_de: 'Höchstgelegene GG-Lage des Rheingaus. Ein kühles Mikroklima erzeugt ausgeprägte Säure und subtile Würze — charakteristisch für das Rauenthaler Terroir.'
  },
  {
    id: 'grafenberg',
    name: 'Kiedricher Gräfenberg',
    village: 'Kiedrich',
    type: 'GG',
    lat: 50.0432, lng: 8.1138,
    estate: 'Weingut Robert Weil',
    grape: 'Riesling',
    soil: 'Phyllitschiefer mit Quarzadern',
    altitude: '180–240 m',
    slope: 'Süd, Südost',
    tours: ['Tasting', 'Vineyard Walk', 'Cellar Tour'],
    desc_en: 'The flagship vineyard of Robert Weil. Consistently produces complex, elegant Rieslings with exceptional depth and a silky mineral finish.',
    desc_de: 'Flaggschiff-Weinberg von Robert Weil. Erzeugt beständig komplexe, elegante Rieslinge mit außergewöhnlicher Tiefe und einem seidigen mineralischen Abgang.'
  },
  {
    id: 'hollenberg',
    name: 'Assmannshäuser Höllenberg',
    village: 'Assmannshausen',
    type: 'GG',
    lat: 49.9882, lng: 7.8912,
    estate: 'Weingut Georg Breuer / August Kesseler',
    grape: 'Spätburgunder',
    soil: 'Roter Phyllitschiefer',
    altitude: '100–200 m',
    slope: 'Süd, Südost',
    tours: ['Tasting', 'Cellar Tour'],
    desc_en: 'The only red-wine GG site in the Rheingau. Pinot Noir on red Phyllit slate produces an elegant, Burgundy-inspired style unique in Germany.',
    desc_de: 'Einzige Rotwein-GG-Lage im Rheingau. Spätburgunder auf rotem Phyllitschiefer ergibt einen eleganten, Burgund-inspirierten Stil, einzigartig in Deutschland.'
  },
  {
    id: 'rothenberg',
    name: 'Geisenheimer Rothenberg',
    village: 'Geisenheim',
    type: 'GG',
    lat: 49.9848, lng: 7.9658,
    estate: 'Weingut Wegeler',
    grape: 'Riesling',
    soil: 'Lehm, Sand, Kies über Grauwacke',
    altitude: '90–130 m',
    slope: 'Süd',
    tours: ['Tasting'],
    desc_en: 'A magnificent south-facing slope above the Rhine. Produces full-bodied, ripe Rieslings with substantial fruit weight and creamy texture.',
    desc_de: 'Prächtige Südhanglage über dem Rhein. Erzeugt vollmundige, reife Rieslinge mit substanziellem Fruchtgewicht und cremiger Textur.'
  },
  {
    id: 'nussbrunnen',
    name: 'Hattenheimer Nussbrunnen',
    village: 'Hattenheim',
    type: 'GG',
    lat: 50.0092, lng: 8.0628,
    estate: 'Weingut Balthasar Ress',
    grape: 'Riesling',
    soil: 'Tiefgründiger Lehm über Mergel',
    altitude: '95 m',
    slope: 'Südost',
    tours: ['Tasting', 'Vineyard Walk', 'Cellar Tour'],
    desc_en: 'A terraced site of exceptional depth. Renowned for opulent, creamy Riesling structure and the characteristic "Nussbrunnen" mineral spring note.',
    desc_de: 'Terrassenlage mit außergewöhnlicher Tiefgründigkeit. Bekannt für opulente, cremige Rieslingstruktur und die charakteristische mineralische "Nussbrunnennote".'
  },
  {
    id: 'domdechanei',
    name: 'Hochheimer Domdechanei',
    village: 'Hochheim',
    type: 'GG',
    lat: 50.0096, lng: 8.3524,
    estate: 'Domdechant Werner',
    grape: 'Riesling',
    soil: 'Lösslehm, sandig-lehmig',
    altitude: '95–110 m',
    slope: 'Süd',
    tours: ['Tasting', 'Cellar Tour'],
    desc_en: 'The easternmost GG site in the Rheingau, bordering the Main. Warm, full-bodied wines with generous fruit and a long, spicy finish.',
    desc_de: 'Östlichste GG-Lage des Rheingaus, grenzt an den Main. Warme, vollmundige Weine mit generöser Frucht und langem, würzigem Abgang.'
  },
  {
    id: 'jesuitengarten',
    name: 'Winkeler Jesuitengarten',
    village: 'Winkel',
    type: 'GG',
    lat: 49.9985, lng: 8.0138,
    estate: 'Weingut Wegeler / Fritz Allendorf',
    grape: 'Riesling',
    soil: 'Lösslehm über Kies',
    altitude: '88 m',
    slope: 'Süd',
    tours: ['Tasting', 'Vineyard Walk'],
    desc_en: 'A historic Jesuit monastery vineyard. Produces fine, elegant Riesling with a characteristic floral bouquet and delicate mineral structure.',
    desc_de: 'Historische Klosterlage der Jesuiten. Feiner, eleganter Riesling mit charakteristischem Blütenbukett und zarter mineralischer Struktur.'
  },

  /* ── Erstes Gewächs (1G) ───────���────────────────────────────────────────── */
  {
    id: 'steinberg',
    name: 'Steinberg (Kloster Eberbach)',
    village: 'Hattenheim',
    type: '1G',
    lat: 50.0388, lng: 8.1552,
    estate: 'Hessische Staatsweingüter Kloster Eberbach',
    grape: 'Riesling',
    soil: 'Devonischer Schiefer',
    altitude: '160–220 m',
    slope: 'Süd, Südost',
    tours: ['Tasting', 'Vineyard Walk', 'Cellar Tour'],
    desc_en: 'A walled Cistercian monastery vineyard (Clos) of extraordinary historical significance, founded in 1135. The 1G from this site is a benchmark of German viticulture.',
    desc_de: 'Ummauerte Zisterzienserklosterlage (Clos) von au��ergewöhnlicher historischer Bedeutung, gegründet 1135. Das 1G gilt als Maßstab des deutschen Weinbaus.'
  },
  {
    id: 'rottland',
    name: 'Rüdesheimer Berg Rottland',
    village: 'Rüdesheim',
    type: '1G',
    lat: 49.9802, lng: 7.9202,
    estate: 'Weingut Leitz / Josef Spreitzer',
    grape: 'Riesling',
    soil: 'Schiefer, Quarzit',
    altitude: '80–200 m',
    slope: 'Süd',
    tours: ['Tasting', 'Vineyard Walk'],
    desc_en: 'A steep slate slope adjacent to Berg Schlossberg. Produces powerful, mineral Rieslings with firm acidity and impressive concentration.',
    desc_de: 'Steile Schieferlage angrenzend an den Schlossberg. Kräftiger, mineralischer Riesling mit fester Säure und beeindruckender Konzentration.'
  },
  {
    id: 'jungfer',
    name: 'Hallgartener Jungfer',
    village: 'Hallgarten',
    type: '1G',
    lat: 50.0148, lng: 8.0805,
    estate: 'Weingut Ress / Fürst Löwenstein',
    grape: 'Riesling',
    soil: 'Tonschiefer, Lehm',
    altitude: '120–160 m',
    slope: 'Süd, Südost',
    tours: ['Tasting'],
    desc_en: 'A classic Rheingau hillside site. Elegant Riesling with mineral coolness and a refined, persistent finish.',
    desc_de: 'Klassische Rheingauer Hängenlage. Eleganter Riesling mit mineralischer Kühle und einem verfeinerten, langanhaltenden Abgang.'
  },
  {
    id: 'sonnenberg',
    name: 'Eltville Sonnenberg',
    village: 'Eltville',
    type: '1G',
    lat: 50.0231, lng: 8.1128,
    estate: 'Schloss Eltz / Hessische Staatsweingüter',
    grape: 'Riesling',
    soil: 'Lösslehm, Mergel',
    altitude: '100 m',
    slope: 'Süd',
    tours: ['Tasting', 'Vineyard Walk', 'Cellar Tour'],
    desc_en: 'A south-exposed slope near the historic Altstadt of Eltville. Ripe, approachable Riesling with generous texture and sunny fruit character.',
    desc_de: 'Südexponierte Hängelage nahe der historischen Altstadt von Eltville. Reifer, zugänglicher Riesling mit generöser Textur und sonnigem Fruchtcharakter.'
  }
];
